services:
  apache:
    build:
      context: ./apache/
      dockerfile: dockerfile
    container_name: apache
    ports:
      - "80:80"
  mail:
    build:
      context: ./mail/
      dockerfile: dockerfile
    container_name: mail